/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_midea_asr_Config */

#ifndef _Included_com_midea_asr_Config
#define _Included_com_midea_asr_Config
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
