/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_midea_asr_Decoder */

#ifndef _Included_com_midea_asr_Decoder
#define _Included_com_midea_asr_Decoder
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
