/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.8
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.midea.asr;

public class Decoder {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected Decoder(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(Decoder obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        PocketSphinxJNI.delete_Decoder(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public Decoder() {
    this(PocketSphinxJNI.new_Decoder__SWIG_0(), true);
  }

  public Decoder(Config config) {
    this(PocketSphinxJNI.new_Decoder__SWIG_1(Config.getCPtr(config), config), true);
  }

  public static Config defaultConfig() {
    long cPtr = PocketSphinxJNI.Decoder_defaultConfig();
    return (cPtr == 0) ? null : new Config(cPtr, true);
  }

  public void startUtt() {
    PocketSphinxJNI.Decoder_startUtt(swigCPtr, this);
  }

  public int processRaw(short[] SDATA, long NSAMP, boolean no_search, boolean full_utt) {
    return PocketSphinxJNI.Decoder_processRaw(swigCPtr, this, SDATA, NSAMP, no_search, full_utt);
  }

  public void endUtt() {
    PocketSphinxJNI.Decoder_endUtt(swigCPtr, this);
  }

  public String segThreshold(int threshold, String orderfilename) {
    return PocketSphinxJNI.Decoder_segThreshold(swigCPtr, this, threshold, orderfilename);
  }

  public int getscore(String hyp) {
    return PocketSphinxJNI.Decoder_getscore(swigCPtr, this, hyp);
  }

}
